---
#copy cluster.cnf file to all nodes
- name: copy galera config
  template:
      src: galera.cnf.j2
      dest: /etc/mysql/conf.d/galera.cnf
      owner: root
      mode: 0644

#stop server on all nodes
- name: Stop MariaDB on first MariaDB Galera cluster node
  service: name=mariadb state=stopped

#bootstrap cluster from node1
- name: Bootstrap first MariaDB Galera cluster node
  command: galera_new_cluster
  when: ansible_enp0s8.ipv4.address == groups['nodes'][0]

#start the servers on all nodes
- name: start the other MariaDB Galera cluster nodes
  service: name=mariadb state=started